This Note compares performance of [base SNLI trained Electra Model] versus [Electra model trained on combined SNLI+ANLI data from scratch - Approach A2]

In [1]:
import os

# Change to a mounted drive, for example, /mnt/my_drive
os.chdir('E:\\NLP\\Comparison')

In [2]:
pwd

'E:\\NLP\\Comparison'

In [3]:
ls

 Volume in drive E is Sid_2023
 Volume Serial Number is E065-686B

 Directory of E:\NLP\Comparison

12/04/2023  04:31 AM    <DIR>          .
12/04/2023  04:31 AM    <DIR>          ..
12/04/2023  03:22 AM           733,215 eval_predictions_a0_r1.jsonl
12/04/2023  03:23 AM           731,548 eval_predictions_a0_r2.jsonl
12/04/2023  03:24 AM           842,629 eval_predictions_a0_r3.jsonl
12/04/2023  03:19 AM           732,853 eval_predictions_a1_r1.jsonl
12/04/2023  03:18 AM           731,140 eval_predictions_a1_r2.jsonl
12/04/2023  03:20 AM           842,687 eval_predictions_a1_r3.jsonl
12/04/2023  04:23 AM         2,564,951 eval_predictions_SNLI_old_model.jsonl
12/04/2023  04:26 AM         2,567,693 eval_predictions_SNLI_updated_with_ANLI.jsonl
12/04/2023  04:21 AM         2,565,061 eval_predictions_SNLIpANLIm_SNLIval.jsonl
               9 File(s)     12,311,777 bytes
               2 Dir(s)  1,866,577,178,624 bytes free

In [4]:
import pandas as pd
df_base = pd.read_json('eval_predictions_SNLI_old_model.jsonl', lines=True)
df_base.head()

,premise,hypothesis,label,predicted_scores,predicted_label
0,Two women are embracing while holding to go pa...,The sisters are hugging goodbye while holding ...,1,"[-2.655517339706421, 4.35628080368042, -2.9564...",1
1,Two women are embracing while holding to go pa...,Two woman are holding packages.,0,"[3.999716997146606, -0.908149480819702, -3.110...",0
2,Two women are embracing while holding to go pa...,The men are fighting outside a deli.,2,"[-4.539059162139893, -2.610094308853149, 5.717...",2
3,"Two young children in blue jerseys, one with t...",Two kids in numbered jerseys wash their hands.,0,"[3.978000879287719, -1.148713946342468, -2.775...",0
4,"Two young children in blue jerseys, one with t...",Two kids at a ballgame wash their hands.,1,"[-3.37094497680664, 2.595725297927856, -0.2479...",1

In [5]:
import pandas as pd
df_a1 = pd.read_json('eval_predictions_SNLI_updated_with_ANLI.jsonl', lines=True)
df_a1.head()

,premise,hypothesis,label,predicted_scores,predicted_label
0,Two women are embracing while holding to go pa...,The sisters are hugging goodbye while holding ...,1,"[-4.015252590179443, 4.470546245574951, -1.911...",1
1,Two women are embracing while holding to go pa...,Two woman are holding packages.,0,"[2.888674736022949, -2.042037963867187, -0.795...",0
2,Two women are embracing while holding to go pa...,The men are fighting outside a deli.,2,"[-4.105733871459961, -1.17663288116455, 3.9173...",2
3,"Two young children in blue jerseys, one with t...",Two kids in numbered jerseys wash their hands.,0,"[1.355234861373901, -2.21549916267395, 1.08333...",0
4,"Two young children in blue jerseys, one with t...",Two kids at a ballgame wash their hands.,1,"[-2.860575914382934, -2.119940996170044, 3.986...",2

In [6]:
len(df_base)

9842

In [7]:
import pandas as pd
df_a2 = pd.read_json('eval_predictions_SNLI_updated_with_ANLI.jsonl', lines=True)
df_a2.head()

,premise,hypothesis,label,predicted_scores,predicted_label
0,Two women are embracing while holding to go pa...,The sisters are hugging goodbye while holding ...,1,"[-4.015252590179443, 4.470546245574951, -1.911...",1
1,Two women are embracing while holding to go pa...,Two woman are holding packages.,0,"[2.888674736022949, -2.042037963867187, -0.795...",0
2,Two women are embracing while holding to go pa...,The men are fighting outside a deli.,2,"[-4.105733871459961, -1.17663288116455, 3.9173...",2
3,"Two young children in blue jerseys, one with t...",Two kids in numbered jerseys wash their hands.,0,"[1.355234861373901, -2.21549916267395, 1.08333...",0
4,"Two young children in blue jerseys, one with t...",Two kids at a ballgame wash their hands.,1,"[-2.860575914382934, -2.119940996170044, 3.986...",2

In [9]:
import pandas as pd

# Assuming df_base and df_a1 are your DataFrames

# Step 1: Merge the DataFrames on 'premise' and 'hypothesis'
merged_df = pd.merge(df_base, df_a2, on=['premise', 'hypothesis'], suffixes=('_base', '_a1'))

# Step 2: Filter rows where label matches predicted_label in df_base but not in df_a1
filtered_df = merged_df[
    (merged_df['label_base'] != merged_df['predicted_label_base']) &
    (merged_df['label_a1'] == merged_df['predicted_label_a1'])
]

# Step 3: Selecting relevant columns (optional)
# You can modify this list to include the columns you're interested in
columns_to_display = ['premise', 'hypothesis', 'label_base', 'predicted_label_base', 'label_a1', 'predicted_label_a1']
result_df = filtered_df[columns_to_display]

# Display the result
result_df

,premise,hypothesis,label_base,predicted_label_base,label_a1,predicted_label_a1
22,Two men on bicycles competing in a race.,Men are riding bicycles on the street.,1,0,1,1
29,Families waiting in line at an amusement park ...,People are waiting to see a movie.,2,1,2,2
68,A taxi SUV drives past an urban construction s...,A man is chasing an SUV that is going in the s...,2,1,2,2
77,A shirtless man is singing into a microphone w...,He is Polish.,1,2,1,1
112,A man wearing sunglasses is sitting on the ste...,"The man is reading a spoon with the words ""HEL...",2,1,2,2
...,...,...,...,...,...,...
9719,Two men boxing a ring while one boxer is hitti...,They are in a boxing match.,0,1,0,0
9721,A man wearing a red bicycle helmet talking on ...,A man talks on his walky talky.,2,1,2,2
9757,A woman in a pink shirt is painting the last t...,The woman is using different colors,1,0,1,1
9793,Two children in a bag race competing against e...,The boy watching has a broken leg.,1,2,1,1
9828,Child squirting paint onto a piece of spin-art.,The child has paint all over their hands.,1,0,1,1

In [12]:
len(result_df)/9842.0

0.029770371875635034

In [17]:
# Filter result_df based on specific conditions
final_df = result_df[
    (result_df['label_base'] == 0) &
    (result_df['predicted_label_base'] == 1) &
    (result_df['predicted_label_a1'] == 0)
]

# Display the final DataFrame
final_df

,premise,hypothesis,label_base,predicted_label_base,label_a1,predicted_label_a1
271,A boy looks surly as his father looks at the c...,a boy looks at his farther,0,1,0,0
411,This mother and her daughter and granddaughter...,The car that belongs to the family is having i...,0,1,0,0
443,A hispanic fruit market with many different fr...,A fruit market is selling vegetables,0,1,0,0
498,An indian man walks past a temple on his way t...,A man is heading to his house of worship.,0,1,0,0
775,A little girl in a red flowered dress with a t...,A little girl in red plays tennis.,0,1,0,0
790,A young girl wearing a pink coat plays with a ...,A kid is swinging a toy golf club.,0,1,0,0
879,Woman being photographed near a bicycle.,Someone is shooting a photo.,0,1,0,0
909,Five little boys are playing baseball.,A few little boys playing baseball outside.,0,1,0,0
1089,Women are standing outside,There are muliple women outdoors.,0,1,0,0
1119,A young man plays a racing video game.,a young man is staring at a screen,0,1,0,0
1265,A female dancer works on striking a pose.,The woman is practicing modeling.,0,1,0,0
1472,A couple is a standing together the woman is a...,People are going to a wedding.,0,1,0,0
1521,A woman in a yellow dress transporting picked ...,A woman transports her crops from the fields,0,1,0,0
2619,girl sitting in fire for a show,The girl is a performer for the show.,0,1,0,0
2960,A large group of people stand outside on a roa...,One group of people are watching what another ...,0,1,0,0
3215,A soccer team dressed in all black are gathere...,Some players are playing soccer in ground,0,1,0,0
3252,A man riding a dirt bike on a racetrack.,A man is riding a dirt bike in a race at a track.,0,1,0,0
3263,An elderly saxophonist performing at an outdoo...,An elder performs an intrumental piece at an e...,0,1,0,0
3661,Two backpackers look at scenic mountains.,Two guys are carrying things on their back.,0,1,0,0
3732,This football team wears red shirts and red he...,They are playing football.,0,1,0,0
4457,A man with a blue shirt and glasses points to ...,The man is attempting to draw attention to a p...,0,1,0,0
4680,"A boy hits a ball, with a bat, outside, while ...",The kid is hitting a baseball.,0,1,0,0
4827,Black greyhound dog racing down a track.,The dog is in a race.,0,1,0,0
5085,A race car driver leaps from a burning car.,A race car driver escaping danger.,0,1,0,0
5117,A mom is taking a picture with her two small d...,Mom is taking a family photo.,0,1,0,0
5557,A shopper buys cat food at a Walmart,A person shops for their pet at a store.,0,1,0,0
5599,The group is working with microscopes and wear...,Some people are looking at something through m...,0,1,0,0
5670,A young man rolling up the sleeves on his swea...,The teenager touches his sweater.,0,1,0,0
5765,A person in an orange kayak navigates white wa...,A PERSON IS KAYAKING IN ROUGH WATERS.,0,1,0,0
6371,Little kids enjoy sprinklers by running throug...,Children are getting wet on purpose.,0,1,0,0
6423,Two indian men are dancing in suits with an in...,The people are Indian.,0,1,0,0
6688,Boys on a field playing flag football with one...,A boy attempts to tackle an opposing player in...,0,1,0,0
7345,Three girls fell on top of one another and are...,Three girls laughing about clumsily falling on...,0,1,0,0
7762,"Four men are playing soccer, two in white jers...",Two opposing teams that are playing soccer hav...,0,1,0,0
7897,Woman helps bride into dress.,A woman helps a bride dress herself.,0,1,0,0
8586,A group of people wearing light blue shirts an...,A group of people in similar clothing are awar...,0,1,0,0
9109,A man speaking or singing into a microphone wh...,An entertainer is tickling the ivories.,0,1,0,0
9192,A light colored dog splashes through the water.,The dog is having fun in the water.,0,1,0,0
9587,A man wearing an apron is smiling at a plate o...,The man is happy by the sight of the food befo...,0,1,0,0
9594,A man and woman sit on a dock looking out over...,The day is gloomy and poorly lit.,0,1,0,0
9616,People of another country are gathered at the ...,Foreigners are assembled at a market.,0,1,0,0
9622,A dog running in the sand.,A dog is running outside at the beach.,0,1,0,0
9719,Two men boxing a ring while one boxer is hitti...,They are in a boxing match.,0,1,0,0

In [18]:
len(final_df)/len(result_df)

0.14675767918088736

In [20]:
# Filter result_df based on specific conditions
final_df = result_df[
    (result_df['label_base'] == 0) &
    (result_df['predicted_label_base'] == 2) &
    (result_df['predicted_label_a1'] == 0)
]

# Display the final DataFrame
final_df
len(final_df)/len(result_df)

0.027303754266211604

In [21]:
# Filter result_df based on specific conditions
final_df = result_df[
    (result_df['label_base'] == 1) &
    (result_df['predicted_label_base'] == 2) &
    (result_df['predicted_label_a1'] == 1)
]

# Display the final DataFrame
final_df
#len(final_df)/len(result_df)

,premise,hypothesis,label_base,predicted_label_base,label_a1,predicted_label_a1
77,A shirtless man is singing into a microphone w...,He is Polish.,1,2,1,1
140,A young boy with black hair is holding onto a ...,The boy is outside and running from cops.,1,2,1,1
357,Two boys stand in an ocean as the sun sets.,The boys are surfing,1,2,1,1
394,Four young men sit on the floor close to a tel...,Four males are sitting indoors because it's ra...,1,2,1,1
406,People dressed in costumes walking down a street.,People dressed up in costumes preparing to rob...,1,2,1,1
...,...,...,...,...,...,...
9295,Javelin competition,The javelin competition was cancelled due to r...,1,2,1,1
9376,A race car sits in the pits.,The car is being repaired.,1,2,1,1
9527,Two men stand in an electric outdoor lift.,"The two men are inspectors for the FDA, waitin...",1,2,1,1
9576,Football players playing in mud.,Football players are wrestling in mud.,1,2,1,1
9793,Two children in a bag race competing against e...,The boy watching has a broken leg.,1,2,1,1

In [22]:
len(final_df)/len(result_df)

0.37542662116040953

In [23]:
# Filter result_df based on specific conditions
final_df = result_df[
    (result_df['label_base'] == 2) &
    (result_df['predicted_label_base'] == 0) &
    (result_df['predicted_label_a1'] == 2)
]

# Display the final DataFrame
final_df
#len(final_df)/len(result_df)

,premise,hypothesis,label_base,predicted_label_base,label_a1,predicted_label_a1
425,"A woman holds her child out of a red window, n...",The TV holds a woman who holds a child.,2,0,2,2
561,Man in a military outfit handing something in ...,A man in civilian clothes hands a bag to a gro...,2,0,2,2
719,Three men look on as two other men carve up a ...,Other look while a man carves beef,2,0,2,2
782,"There are three men in this picture, two are o...",Three men are on motorcycles.,2,0,2,2
945,"Inside the igloo, the young man gets ready for...",The young man gets ready to leave.,2,0,2,2
1008,A photographer snaps a midair action shot of a...,The midair shot snaps at a boarder of snow.,2,0,2,2
1101,A distant person is climbing up a very sheer m...,The mountain is unclimbable for humans.,2,0,2,2
1482,One man dressed in a martial arts uniform kick...,The man kicks the umpire.,2,0,2,2
1824,A man in a pink shirt is stealing an old coupl...,A couple is giving a man a bike as a gift.,2,0,2,2
1904,"A young women, in a black shirt, is holding a ...",A young woman and young boy are holding hands.,2,0,2,2
2585,A boy in a blue shirt looks away from the came...,A boy looks into the camera while a girl looks...,2,0,2,2
3365,Flaming are shooting from the rear of a race car.,Flames are shooting from the front of a race car.,2,0,2,2
3426,Three Oklahoma Sooners playing football agains...,A group of bears are playing a football game.,2,0,2,2
3978,"A man in a backwards baseball cap, black shirt...",The cap is forwards.,2,0,2,2
4076,a woman in green stands with her hands on her ...,A woman is raising her hands up.,2,0,2,2
4164,Two construction workers in a truck having a c...,Two people are outside a truck.,2,0,2,2
4504,Two children lined up outside in a grassy fiel...,Two kids were in a field with their arms down.,2,0,2,2
4679,"A man in a blue shirt, khaki shorts, ball cap ...","A man in a blue shirt, khaki shorts, ball cap ...",2,0,2,2
5138,"Four people, One male in a blue shirt and slac...","Four people, One male in a blue shirt and slac...",2,0,2,2
5273,A young man is holding a small boy who is wear...,A man is holding a purse,2,0,2,2
5322,A man and a woman are competing in a road rice.,A man and women fighting,2,0,2,2
5379,"A man sits in a dingy stall which says ""Sol Se...","A still sits in a dingy man which says ""why"" o...",2,0,2,2
5401,It's Summer time and two girls play with bubbl...,They are on the boat dock.,2,0,2,2
5776,The white dog with brown spots is walking thro...,The white and brown dog is standing on the edg...,2,0,2,2
6103,Big hairy dog chews on a bone while lying on a...,The dog is laying on a pointy object,2,0,2,2
6737,One kid is running across a field carrying a f...,Two children run in different directions.,2,0,2,2
7598,The room full of youths reacts emotionally as ...,a room of kids dancing.,2,0,2,2
7673,A sumo wrestler accepting an award.,A wrestler is fighting.,2,0,2,2
8474,Dog standing with 1 foot up in a large field.,The dog is standing on one leg.,2,0,2,2
8998,A group of women observe as two men attempt to...,The women fix bikes as men watch.,2,0,2,2

In [24]:
len(final_df)/len(result_df)

0.10238907849829351

In [26]:
# Filter result_df based on specific conditions
final_df = result_df[
    (result_df['label_base'] == 1) &
    (result_df['predicted_label_base'] == 0) &
    (result_df['predicted_label_a1'] == 1)
]

# Display the final DataFrame
final_df

,premise,hypothesis,label_base,predicted_label_base,label_a1,predicted_label_a1
22,Two men on bicycles competing in a race.,Men are riding bicycles on the street.,1,0,1,1
123,Two black little boys hanging over an upside d...,the children are outside.,1,0,1,1
264,A man poses for a photo in front of a Chinese ...,The man has experience in taking photos.,1,0,1,1
369,A child is looking out of a door.,The door is open.,1,0,1,1
528,Two kids are standing in the ocean hugging eac...,Two kids enjoy their day at the beach.,1,0,1,1
...,...,...,...,...,...,...
9228,People work diligently on there computers at t...,Inside the office building several people comp...,1,0,1,1
9277,Santa Claus being photographed at a holiday me...,Santa Claus is the center of attention as usual.,1,0,1,1
9606,A balding man is getting his shoes cleaned on ...,An old man getting his shoes shined.,1,0,1,1
9757,A woman in a pink shirt is painting the last t...,The woman is using different colors,1,0,1,1
9828,Child squirting paint onto a piece of spin-art.,The child has paint all over their hands.,1,0,1,1

In [27]:
len(final_df)/len(result_df)

0.21160409556313994

In [28]:
# Filter result_df based on specific conditions
final_df = result_df[
    (result_df['label_base'] == 0) &
    (result_df['predicted_label_base'] == 0) &
    (result_df['predicted_label_a1'] == 1)
]

# Display the final DataFrame
final_df
#len(final_df)/len(result_df)

,premise,hypothesis,label_base,predicted_label_base,label_a1,predicted_label_a1
86,The two farmers are working on a piece of John...,Men are working on John Deere equipment,0,0,0,1
117,A person powerwashing stairs leading down to a...,a worker cleans near the pool,0,0,0,1
128,A group of people prepare hot air balloons for...,A group of people are outside.,0,0,0,1
232,Number 13 kicks a soccer ball towards the goal...,A player trying to score in a soccer game.,0,0,0,1
261,A man is a safety suit walking outside while a...,There are two men walking outside.,0,0,0,1
...,...,...,...,...,...,...
9461,The lady wearing a red coat is giving a speech.,Woman is the center of attention.,0,0,0,1
9465,A nurse examines equipment in the operating room.,A nurse at work.,0,0,0,1
9542,A boy and dog are on the lawn outside of the h...,A boy and dog play outside.,0,0,0,1
9613,A soldier is holding a gun and crouched down w...,A man is holding a gun.,0,0,0,1
9657,"Two competitors in the last leg of a race, str...",Races can be long and tiring.,0,0,0,1

In [29]:
len(final_df)/len(result_df)

0.16554379210779596